{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "helios-operator.fullname" . }}-metrics
  namespace: {{ .Values.metrics.serviceMonitor.namespace | default (include "helios-operator.namespace" .) }}
  labels:
    {{- include "helios-operator.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "helios-operator.annotations" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "helios-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
  endpoints:
  - port: https
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
    scheme: https
    path: /metrics
    tlsConfig:
      insecureSkipVerify: true
{{- end }}
