apiVersion: platform.helios.io/v1
kind: HeliosApp
metadata:
  name: helios-app
  namespace: helios-apps
spec:
  # --- Git source repository ---
  gitRepo: "https://github.com/PhuocHoan/helios.git" # <-- URL repo của bạn
  gitBranch: "main"

  # --- GitOps repository ---
  gitopsRepo: "https://github.com/PhuocHoan/helios-gitops.git" # <-- URL GitOps repo
  gitopsPath: "helios-app" # Optional, defaults to app name if omitted
  gitopsBranch: "main"

  # --- Image configuration ---
  imageRepo: "docker/hophuochoan/helios" # <-- Nơi bạn muốn lưu image
  port: 80
  replicas: 1

  # --- Tekton configuration ---
  serviceAccount: "pipeline-sa" # Tên Service Account cho pipeline
  webhookSecret: "github-webhook-secret" # Tên secret chứa mã webhook
  pvcName: "helios-pvc"
