---
# Kustomization for Helios Operator Monitoring Resources
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helios-system

resources:
  - servicemonitor.yaml
  - prometheus-rules.yaml

labels:
  - pairs:
      app.kubernetes.io/name: helios-operator
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/part-of: helios-operator
